# Generated by Django 4.1 on 2022-08-28 09:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('is_driver', models.BooleanField(default=False)),
                ('_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StopPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('x', models.CharField(blank=True, max_length=100, null=True)),
                ('y', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('distance', models.CharField(blank=True, max_length=100, null=True)),
                ('after_hours_start', models.BooleanField(default=False)),
                ('average_speed', models.CharField(blank=True, max_length=100, null=True)),
                ('maximum_speed', models.IntegerField(blank=True, null=True)),
                ('after_hours_stop_duration', models.CharField(blank=True, max_length=100, null=True)),
                ('speed_range1_duration', models.CharField(blank=True, max_length=100, null=True)),
                ('work_stop_duration', models.CharField(blank=True, max_length=100, null=True)),
                ('driving_duration', models.CharField(blank=True, max_length=100, null=True)),
                ('_id', models.CharField(blank=True, max_length=100, null=True)),
                ('idling_duration', models.CharField(blank=True, max_length=100, null=True)),
                ('after_hours_distance', models.CharField(blank=True, max_length=100, null=True)),
                ('start', models.CharField(blank=True, max_length=100, null=True)),
                ('speed_range2', models.CharField(blank=True, max_length=100, null=True)),
                ('speed_range3', models.CharField(blank=True, max_length=100, null=True)),
                ('engine_hours', models.CharField(blank=True, max_length=100, null=True)),
                ('speed_range1', models.CharField(blank=True, max_length=100, null=True)),
                ('stop_duration', models.CharField(blank=True, max_length=100, null=True)),
                ('is_seat_belt_off', models.BooleanField(default=False)),
                ('speed_range2_duration', models.CharField(blank=True, max_length=100, null=True)),
                ('speed_range3_duration', models.CharField(blank=True, max_length=100, null=True)),
                ('next_trip_start', models.CharField(blank=True, max_length=100, null=True)),
                ('stop', models.CharField(blank=True, max_length=100, null=True)),
                ('after_hours_driving_duration', models.CharField(blank=True, max_length=100, null=True)),
                ('work_driving_duration', models.CharField(blank=True, max_length=100, null=True)),
                ('after_hour_send', models.BooleanField(default=False)),
                ('work_distance', models.CharField(blank=True, max_length=100, null=True)),
                ('base_table_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.basetable')),
            ],
        ),
        migrations.RemoveField(
            model_name='customparameters',
            name='result_id',
        ),
        migrations.RemoveField(
            model_name='deviceflags',
            name='result_id',
        ),
        migrations.RemoveField(
            model_name='deviceplanbillinginfo',
            name='result_id',
        ),
        migrations.RemoveField(
            model_name='groups',
            name='result_id',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='base_table_id',
        ),
        migrations.RemoveField(
            model_name='worktime',
            name='result_id',
        ),
        migrations.DeleteModel(
            name='CustomFeatures',
        ),
        migrations.DeleteModel(
            name='CustomParameters',
        ),
        migrations.DeleteModel(
            name='DeviceFlags',
        ),
        migrations.DeleteModel(
            name='DevicePlanBillingInfo',
        ),
        migrations.DeleteModel(
            name='Groups',
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
        migrations.DeleteModel(
            name='WorkTime',
        ),
        migrations.AddField(
            model_name='stoppoint',
            name='trip_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reports.trips'),
        ),
        migrations.AddField(
            model_name='driver',
            name='trip_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reports.trips'),
        ),
        migrations.AddField(
            model_name='device',
            name='trip_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reports.trips'),
        ),
    ]
