# Generated by Django 4.1 on 2022-08-28 10:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_device_driver_stoppoint_trips_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exceptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('distance', models.CharField(max_length=100)),
                ('active_to', models.CharField(max_length=100)),
                ('active_from', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('last_modified_datetime', models.CharField(max_length=100)),
                ('driver', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('_id', models.CharField(max_length=100)),
                ('base_table_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.basetable')),
            ],
        ),
        migrations.AlterField(
            model_name='device',
            name='trip_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.trips'),
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('_id', models.CharField(max_length=100)),
                ('exceptions_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reports.exceptions')),
            ],
        ),
        migrations.CreateModel(
            name='Diagnostic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('_id', models.CharField(max_length=100)),
                ('exceptions_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reports.exceptions')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='exceptions_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.exceptions'),
        ),
    ]
