# Generated by Django 3.1 on 2022-08-28 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_exceptions_alter_device_trip_id_rule_diagnostic_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeneralReport',
        ),
        migrations.AlterField(
            model_name='device',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='exceptions',
            name='active_from',
            field=models.DateTimeField(max_length=100),
        ),
        migrations.AlterField(
            model_name='exceptions',
            name='active_to',
            field=models.DateTimeField(max_length=100),
        ),
        migrations.AlterField(
            model_name='exceptions',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='stoppoint',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='trips',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='trips',
            name='next_trip_start',
            field=models.DateTimeField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trips',
            name='start',
            field=models.DateTimeField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trips',
            name='stop',
            field=models.DateTimeField(blank=True, max_length=100, null=True),
        ),
    ]
