# Generated by Django 3.1 on 2022-08-29 20:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20220828_2154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('_id', models.CharField(blank=True, max_length=100, null=True)),
                ('license_plate', models.CharField(blank=True, max_length=100, null=True)),
                ('base_table_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.basetable')),
            ],
        ),
    ]
