# Generated by Django 3.1 on 2022-08-29 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_vehicle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='_id',
            new_name='geo_tab_id',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='_id',
            new_name='geo_tab_id',
        ),
    ]
